//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace orionpublishers.lp
{


    public partial class audiobook_service
    {

        /// <summary>
        /// LpBannerForm43431 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::orionpublishers.includes.LpBannerForm LpBannerForm43431;

        /// <summary>
        /// LpPopupForm4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::orionpublishers.includes.LpPopupForm LpPopupForm4;
    }
}
